spring.application.name=Spring-Producer-Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.name=chuwa-yyds
spring.kafka.consumer.group-id=consumer_group_1

#Setup port for this Spring application
server.port=8088

# dao config
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=mypassword

# hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update


# disable default auto-commit to use acknowledge
spring.kafka.consumer.enable-auto-commit=false
# when consumer never commit offsets or the offsets expired, consumer read the earliest message available
spring.kafka.consumer.auto-offset-reset=earliest
# only can config manual commit here when you use default kafkaListenerContainerFactory
#spring.kafka.listener.ack-mode=manual

